# Nearest centroid classifier 
In this jupyter notebook, I am going to implement nearesest centroid classifier as a part of machine learning class in my university

In [30]:
import numpy as np

In [101]:
#import neccessary data
train_y = np.array([0,1,0,0,1,1,1])
train_x = np.array([[10,20,10],[50,60, 1],[8,11,34],[7,14,23],[55,65,2 ],[49,63,2],[47,53,0]])
test_x = np.array([[0,0,0],[1,1,1],[50,60,1]])

num_feat = train_x.shape[1]
num_class = len(set(train_y))

In [102]:
mu = np.array([np.zeros(num_feat)]*num_class)
N = np.zeros(num_feat)
mu, N

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([0., 0., 0.]))

In [103]:
for row, label in zip(x,y):
    mu[label] = N[label]/(N[label]+1)*mu[label] + row/(N+1)
    N[label] += 1

In [104]:
def predict_class(x, mu):

    dist = np.sqrt(np.sum((mu-x)**2, axis=1))
    return np.argmin(dist)
    

In [107]:
predict_class([78,40,1],mu)

1

## Try to create a class for a model

In [130]:
class Nearest_centroid:
    def __init__(self, y, x):
        num_feat = x.shape[1]
        num_class = len(set(y))
        self.x = x
        self.y = y
        self.mu = np.array([np.zeros(num_feat)]*num_class)
        self.N = np.zeros(num_feat)
        
    def fit(self):
        for row, label in zip(self.x, self.y):
            self.mu[label] = self.N[label]/(self.N[label]+1)*self.mu[label] + row/(self.N[label]+1)
            self.N[label] += 1
        print(f"Final weights for centroids:")
        for i, mu in enumerate(self.mu):
            print(f"Class {i} centroid: {mu}")
        return print("Done. Ready to predict.")
    
    def predict(self, x):
        dist = [np.sqrt(np.sum((self.mu-item)**2, axis=1)) for item in x]
        result = np.argmin(dist, axis=1)
        
        for X, c in zip(x, result):
            print(f"Predicted class {c} for {X}")
            
        return np.argmin(dist, axis=1)

In [131]:
model = Nearest_centroid(train_y, train_x)
model.fit()

Final weights for centroids:
Class 0 centroid: [ 8.33333333 15.         22.33333333]
Class 1 centroid: [50.25 60.25  1.25]
Done. Ready to predict.


In [132]:
model.predict(test_x)

Predicted class 0 for [0 0 0]
Predicted class 0 for [1 1 1]
Predicted class 1 for [50 60  1]


array([0, 0, 1])

Done.