# Perceptron, own implementation

## Initial thoughts

In [1]:
import numpy as np

n = 10
m = 5
c = 3
alpha = 0.1

data = np.random.random((n, m))
data

array([[0.03798095, 0.61439613, 0.36908806, 0.83276492, 0.61904787],
       [0.34634682, 0.87743732, 0.62353323, 0.94515333, 0.25584886],
       [0.68325232, 0.24182126, 0.64829868, 0.87005144, 0.57656399],
       [0.85060238, 0.70405897, 0.8509097 , 0.85284344, 0.21426654],
       [0.06149859, 0.09363381, 0.73844567, 0.56639185, 0.81304941],
       [0.86793334, 0.11113338, 0.0473088 , 0.63692838, 0.14552822],
       [0.88422422, 0.80610938, 0.49929426, 0.4374911 , 0.56821186],
       [0.09743868, 0.108054  , 0.46830123, 0.65872883, 0.18687934],
       [0.36190803, 0.11259089, 0.24695837, 0.83318347, 0.88016751],
       [0.99647389, 0.34508511, 0.45274663, 0.53217139, 0.44659253]])

In [2]:
labels = np.random.randint(c, size = n)
labels

array([1, 1, 0, 2, 1, 2, 1, 1, 2, 1])

In [3]:
W = np.random.random((c, m))
W

array([[0.81615756, 0.43314083, 0.06907804, 0.0524401 , 0.95943114],
       [0.60798076, 0.10538714, 0.13609275, 0.26610823, 0.29490333],
       [0.9707698 , 0.4491137 , 0.18862157, 0.20241754, 0.91854304]])

In [4]:
data@W.T

array([[0.96021845, 0.54223622, 1.11961078],
       [1.00083326, 0.71486492, 1.27422777],
       [1.30596644, 0.93067635, 1.59988158],
       [1.30825862, 0.99728786, 1.67188507],
       [0.95152612, 0.53824737, 1.1025085 ],
       [0.93279966, 0.75824583, 1.16399787],
       [1.67341768, 0.97448276, 1.92507352],
       [0.37251891, 0.36476525, 0.53644575],
       [1.24935343, 0.7467893 , 1.42559985],
       [1.45040691, 0.97713683, 1.72566227]])

In [5]:
pred = np.argmax(data@W.T, axis=1)
pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
correct = (pred == labels)
correct

array([False, False, False,  True, False,  True, False, False,  True,
       False])

In [7]:
for c, p, l, it in zip(correct,pred, labels, range(n)):
    if not c:
        print(c, p)
        W[p] -= alpha* (data[it]*l)/(it+1)
        W[l] += alpha* (data[it]*l)/(it+1)
        

False 2
False 2
False 2
False 2
False 2
False 2
False 2


In [8]:
W

array([[0.81615756, 0.43314083, 0.06907804, 0.0524401 , 0.95943114],
       [0.65414067, 0.22888867, 0.23646114, 0.42777592, 0.40078078],
       [0.9246099 , 0.32561217, 0.08825318, 0.04074984, 0.81266559]])

In [9]:
pred = np.argmax(data@W.T, axis=1)
pred

array([0, 1, 0, 1, 0, 2, 0, 1, 0, 2])

## Final version

In [22]:
n = 10
m = 5
c = 3

data = np.random.random((n, m))
labels = np.random.randint(c, size = n)
labels

array([2, 1, 1, 2, 0, 2, 0, 0, 1, 1])

In [26]:
def multy_class_perceptron(data, labels, c):
    n, m = data.shape
    W = np.random.random((c, m))
    
    for epoch in range(1, 20):
        
        pred = np.argmax(data@W.T, axis=1)
        correct = pred == labels

        for c, p, l, it in zip(correct,pred, labels, range(n)):
            if not c:
                W[p] -= (data[it]*l)/epoch
                W[l] += (data[it]*l)/epoch
    
    return np.argmax(data@W.T, axis=1), sum(pred==labels)/len(labels)
        
    

In [27]:
multy_class_perceptron(data, labels, c)

(array([2, 1, 1, 2, 1, 2, 1, 1, 1, 1]), 0.7)